apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: nginxweb
    type: production
    ver: v1
spec:
  containers:
  - name: web
    image: nginx:1.16-alpine
  - name: curl
    image: vipin2411/curl
    command: ["/bin/sh", "-c", "while : ;do curl http://localhost:80/; sleep 15; done"]
